### ISSUE TITLE
Написать сценарии для модульного тестирования модели MDiscipline

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#102]
Затрагивает #62
Сценарии для модульного тестирования составлять на вкладке 1/2018 UT
Понимать что Ваши сценарии будут манипулировать не формой, а объектами без бизнес-логики.
То есть проверки публичных полей, идентификаторов или свойств сводяться к тому что-бы проверять их тип данных с которым они должны работать и что они хронят то что в них положили.
По идее методов в модели не должно быть.

**Comment by YuriSilenok** [comment]
@alvhmnv 
[Ознакомьтесь ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/master#%D0%A1%D1%82%D0%BE%D0%BB%D0%B1%D1%86%D1%8B-%D0%B2-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D1%85-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B5%D0%B2)пожалуйста с тем что должно содержаться в столбцах, сценарии нужно переписать в соответствии с этим описанием

**Comment by alvhmnv** [comment]
@YuriSilenok 
Ошибки в столбце - Test Data
или не только это неправильно

**Comment by YuriSilenok** [comment]
Сценарии пишутся для стори, в твоем случае для 62
Test title - написать что тестируется, конкретно какое поле какого класса, как раз то что в указано в Description
Description - описывает особенности, в твоем случае не изменяется
Test Data - у тебя вообще должна быть не заполнено
Steps у тебя должна содержать шаги, в данном случае тебе нужно прописать по шагам как ты будешь проверять
Pre-condition  у тебя должно быть прописано по шагам как создать объект для тестирования

**Comment by YuriSilenok** [comment]
Так, еще раз, сценарии для 62 стори, а не для 102, 102 это таск на написание ценариев, которыми ты будешь тестировать стори 62

**Comment by alvhmnv** [comment]
извиняюсь, упустил этот пункт в замечаниях

**Comment by YuriSilenok** [comment]
И здесь тоже поправить

**Comment by YuriSilenok** [comment]
Может быть присвоить? какого объекта?
> 2. Задать полю Name объекта значение ""

**Comment by YuriSilenok** [comment]
Если учитывать твой прекондишен то шагов у тебя будет ровно 1, и один ожидаемый результат в котором ты должен ожидать тип String
> 1. Получить тип поля Code.   2. Сравнить тип поля Name с типом String 
> Step 2: ИСТИНА

**Comment by alvhmnv** [comment]
а почему не правильно пункт со сравнением
мы же можем использовать Assert потом, чтобы истину или ложь получить
может я просто неправильно заполнил прекондишен, потому что не совсем понял что именно нужно  там

**Comment by YuriSilenok** [comment]
По вашему алгоритму мы всегда должны ожидать истину. Мы должны написать что ожидаем, при тесте получаем фактический результат и тест пройден если ожидаемый результат совпадает с фактическим. В ожидаемом результате можно прописывать увеличение списков, возвращение двумерного массива конкретного содержимого

**Comment by alvhmnv** [comment]
так и не понял
и вообще сценарии не верные или только в ожидаемом результате

**Comment by alvhmnv** [comment]
хорошо, это поправил

**Comment by YuriSilenok** [comment]
Почему вы решили что у ID тип данных String?

**Comment by alvhmnv** [comment]
поторопился

**Comment by YuriSilenok** [comment]
Мне для того что бы понять Вашу логику, почему в прекондишенах, в первом сценарии нет инициализация тестируемого поля, а в других тестах есть?

**Comment by alvhmnv** [comment]
я почему-то думал, что id автоматически задаётся

**Comment by alvhmnv** [comment]
где-то видел пример ваш, по-моему Насте вы показывали как можно создать тестируемый объект, и там это поле не инициализировалось тоже, поэтому подумал, что значение там автоматически есть какое-то уже при создании объекта

**Comment by YuriSilenok** [comment]
Это класс для хранения данных, в нем нет никакой логики, в последствии правильность задания всех полей ляжет на контроллер

**Comment by alvhmnv** [comment]
Не понимаю тогда, почему в вашем примере не инициализируется это поле так же
вот нашёл пример этот

mT = new MTeacher(){ mT.Name = "", mT.Surname = "", mT.MiddleName = "", mT.SizeOfTeachingExperience = 0, mT.AcademicDegree = "", mT.AcademicRank = ""}

Вообще что-то все мимо, не понимаю, что мне нужно исправлять сейчас в сценариях

**Comment by YuriSilenok** [comment]
Я не говорил что нужно исправить, я хотел услышать обоснование того почему ID не инициализируется. Согласно диаграмме дополнительно конструкторы никакие не созданы. И решение о том будет ли инициализироваться поле или нет, это на усмотрение сценариста. Причем существует возможность сделать один прекондишен для нескольких сценариев.

**Comment by alvhmnv** [comment]
Вообще объединить ячейки и прописать один  прекондишен или просто одинаковые везде

**Comment by YuriSilenok** [comment]
Объединить

**Comment by YuriSilenok** [comment]
#62 Называется не так
> issue-62(сценарии для модульного тестирования модели MDiscipline)

Остальное нормально, остальное нормально

**Comment by alvhmnv** [comment]
Поправил

**Comment by YuriSilenok** [comment]
Зачтено
