### ISSUE TITLE
Реализовать метод +AddDiscipline(name:string, code:string):bool из класса CDiscipline

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#109]
Реализовать в ветку issue-109
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Класса CDiscipline еще нет, его мне тоже создать надо?

**Comment by YuriSilenok** [comment]
@TanyaMalis 
Все верно, я перестал делать таски которые создают пустой каркас класса, и тот кто делает первый метод объявляет класс.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
То есть, чтобы сделать метод SaveTeacher, мне нужно будет ждать присоединения этой ветки?

**Comment by YuriSilenok** [comment]
Не будет такой ветки, нужно в Вашей сделать этот класс

**Comment by TanyaMalis** [comment]
@YuriSilenok 
У меня стоит еще реалицая метода SaveTeacher в ветку issue-110, из нее же не будет виден созданный в этой ветке класс, значит там тот же самый класс создать надо?

**Comment by YuriSilenok** [comment]
Да, я потом мержконфликт решу, это не проблема
