### ISSUE TITLE
Написать сценарии для модульного тестирования модели MGroups

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#111]
Затрагивает #99

**Comment by Natalia666503** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494

**Comment by YuriSilenok** [comment]
Название у 99 стори не такое
> issue-99(сценарии для модульного тестирования модели MGroups)

А так в целом все хорошо

**Comment by YuriSilenok** [comment]
Зачтено
Я буду задачи накидывать по старой схеме, те задачи которые останутся не реализованными, а баллы все получены, перекинуть на меня с комментарием что курсовик сдан, или можете перекинуть эти задачи самостоятельно на того человека которому хотите помочь.

**Comment by YuriSilenok** [comment]
@TanyaMalis @NastyaFilyushkina 
Зачтено
Я буду задачи накидывать по старой схеме, те задачи которые останутся не реализованными, а баллы все получены, перекинуть на меня с комментарием что курсовик сдан, или можете перекинуть эти задачи самостоятельно на того человека которому хотите помочь.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Вы мне зачли его в журнале, но это таск не мой, а @Natalia666503

**Comment by YuriSilenok** [comment]
Да, действительно это так. Сейчас все поправлю
