### ISSUE TITLE
Реализовать метод +DeleteDiscipline(ID:Guid):bool из класса CDiscipline

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#117]
Реализовать в ветку issue-117
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Создание этого метода же предыдущий таск

**Comment by YuriSilenok** [comment]
Дубликат
