### ISSUE TITLE
Реализовать public object this[Keys key] из модели MDiscipline

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#118]
Затрагивает #62 
Реализовать в ветку issue-118

[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Ветка не создана

**Comment by YuriSilenok** [comment]
Предлагаю создать ее самостоятельно, [здесь ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/90#issuecomment-399685696)описание

**Comment by TanyaMalis** [comment]
@YuriSilenok 
На основе Testing?

**Comment by YuriSilenok** [comment]
Да, мы ее активно эксплуатируем
