### ISSUE TITLE
Проектирование контроллера для объекта Аудитории

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#120]
На[ диаграмме класса](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) начертить класс реализующий методы для объекты аудитории

**Comment by TanyaMalis** [comment]
https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit

**Comment by YuriSilenok** [comment]
Ссылка на документ есть в описании таска, нет необходимости ее дублировать, тем более в техническом виде, для сценариев это может быть актуально если эта ссылка позволяет сразу перейти непосредственно к тестам.
