### ISSUE TITLE
Реализовать метод +GetData(columnName:string, order:bool):string[,] из класса CDiscipline

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#128]
Реализовать в ветку issue-128
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by YuriSilenok** [comment]
Рекомендую приступать к этой задаче после после реализации #115, так как на основе него вы можете первично получить набор данных в двумерный массив, а потом его сортировать...если конечно пойдете по этому пути

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Курсовик сдан

**Comment by YuriSilenok** [comment]
Доделать

**Comment by Natalia666503** [comment]
@YuriSilenok Я не очень понимаю, что здесь делать надо. Можете, пожалуйста, объяснить или заменить на другой таск?

**Comment by YuriSilenok** [comment]
Посмотреть как это реализовано в других контроллерах,там из-за плохой архитектуры получится копипаст.
