### ISSUE TITLE
Начертить диаграмму классов в нотации UML

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#132]
Чертить в [этот](https://docs.google.com/drawings/d/1tKvef0w5NeM1dLPM_j2UJq8U-fJl_lFHy9hd0rhvPJc/edit?usp=sharing) файл
Файл с кодом [Demo.txt](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2137158/Demo.txt)

**Comment by alvhmnv** [comment]
Что-то сделал, но думаю недочетов много, может что-то ещё и понял неправильно
Укажите на ошибки

**Comment by YuriSilenok** [comment]
Другой таск?
> может что-то ещё

Выявленные недостатки
- [Абстрактый метод и класс не помечены](https://jenyay.net/Programming/Uml)
- по диаграмме у вас модель (M) объекта реализует интерфейс контроллера (C), в коде не так

**Comment by alvhmnv** [comment]
Это поправил. Насчет "ещё", да, если можно, то несколько тасков пожалуйста
и ещё я на почте вопрос по поводу доступа к журналу писал

**Comment by YuriSilenok** [comment]
У вас есть таск по которому нет активности 13 дней
[Это ссылка](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/assigned/alvhmnv) по которой вы сможете посмотреть какие на вас есть таски на этом проекте

**Comment by YuriSilenok** [comment]
по поводу журнала, доступ дал, не забывайте что есть понятие приоритетных задач, и запросы на доступ к журналы не являются таковыми. Соответсвенно сейчас горячая пора ликвидации долгов, и очередь обработки почты увеличена.

**Comment by YuriSilenok** [comment]
Зачтено
