### ISSUE TITLE
Автоматизация сценариев для MGroups

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#134]
Затраггивает #111 #99 
Реализовать в ветку issue-134
Имя тестового файла UT_MGroup

**Comment by Natalia666503** [comment]
@YuriSilenok  у меня 15 версия студии

**Comment by YuriSilenok** [comment]
@serega111198 
Видимо дело не идет из-за незнания языка C#, могу предложить разработку сценариев. Эта задача не требует навыка программирования.
