### ISSUE TITLE
Реализовать метода Insert(model:Model) для класса CGroup унаследованного от класса Controller

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#142]
Реализовать в ветку issue-142
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Поведение**
Метод добавляет новую дисциплину в том случае если поле шифр(cipher) является уникальным и не может быть пустым значениями. Если добавление в таблицу произошло, то метод вернет истину, в других случаях возвращается лож. Поле шифр должно проверять содержание на соответсвие маски. Первые два символа это цифры, далее следует символ черты, множество заглавных букв, одна буква нижнего регистра из (б,м,а,д,с), после одна буква нижнего регистра из (о, з), после символ черта, после 1 или 2 символ цифры и возможна буква нижнего ресистра.

**Comment by YuriSilenok** [comment]
1. выполните для вашей ветки git rebase, за последнее время были существенные изменения.
2. Задачу я переформулирую в связи с этими изменениями. Ждите следующего комментария который будет пояснением к уточненному заданию.

**Comment by YuriSilenok** [comment]
@itword7111 
Образец реализации этого метода можете взять из класса CDiscipline
Если будут вопросы по этому таску, задавайте их хдесь

**Comment by YuriSilenok** [comment]
Добавлено новое описание
> При добавлении новой группы нужно учесть что шифр(cipher) должен быть уникален.

**Comment by YuriSilenok** [comment]
**Обновлено поведение**
Метод добавляет новую дисциплину в том случае если поле шифр(cipher) является уникальным и не может быть пустым значениями. Если добавление в таблицу произошло, то метод вернет истину, в других случаях возвращается лож. Поле шифр должно проверять содержание на соответсвие маски. Первые два символа это цифры, далее следует символ черты, множество заглавных букв, одна буква нижнего регистра из (б,м,а,д,с), после одна буква нижнего регистра из (о, з), после символ черта, после 1 или 2 символ цифры и возможна буква нижнего ресистра.

**Comment by itword7111** [comment]
rebase - это перенести изменение текущей ветки в другую? В какую перенести?

**Comment by itword7111** [comment]
В master?

**Comment by YuriSilenok** [comment]
Нет, в нашем случае смысл другой, ваша ветка должна содержать актуальные изменения ветки Testing. Так как вы делали свою ветку из ветки Testing

**Comment by itword7111** [comment]
я делал в ветке issue-142 
то есть перенести изменения в origin/Testing?

**Comment by itword7111** [comment]
при слиянии появились проблемы в csproj файле

**Comment by YuriSilenok** [comment]
Нужно больше информации.
Скрин ошибки например.
Скорее всего это мержконфликт

**Comment by itword7111** [comment]
![default](https://user-images.githubusercontent.com/38357886/47215795-5d1f4980-d3ab-11e8-8975-703db9141691.PNG)

**Comment by YuriSilenok** [comment]
[скопируйте](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Testing/TimetableOfClasses/TimetableOfClasses.csproj) и выполните коммит только этого файла и продолжите rebase
