### ISSUE TITLE
Реализовать метод +Add(group:MGroup):bool из класса CGroup

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#158]
Реализовать в ветку issue-158
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by blinker44** [comment]
Не могу закрыть или перевесить таск, нет возможности
![image](https://user-images.githubusercontent.com/38395077/47253553-2dc91500-d45d-11e8-947b-3de3cad63f54.png)

**Comment by blinker44** [comment]
Не могу закрыть или перевесить таск, нет возможности
![image](https://user-images.githubusercontent.com/38395077/47253580-987a5080-d45d-11e8-96ee-909b1943d9d4.png)
