### ISSUE TITLE
Автоматизация тестов для метода CTeacher.SaveTeacher(ID:Guid, surname:string, name:string, middleName:string, academicDegree:string, AcademicRank:string, SizeOfTeachingExperience:byte):bool

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#159]
Затрагивает #92 #51 
Реализовать в ветку issue-159
Автоматизироватиь тестовые для story-51 [сценарии] (https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=A53):
При автоматизации этих сценариев нужно помнить что вы тестируете котроллер (контроллер реализует бизнес-логику, ограничение и т.д.). Вам не нужно автоматизировать действия непосредственно с формой. То есть Ваша задача написать такой тест который бы делал все то же самое, но только черерз контроллер.
Имя файла содержащий автотесты UT_CTeacher

**Comment by Whitetech7417** [comment]
@YuriSilenok а что делать? из какой ветки качать проект? как создавать Unit test отдельный проект или добавить в тот который скачаю?

**Comment by YuriSilenok** [comment]
Автоматизировать сценарии которые уже написаны
> а что делать

Сделать свою ветку с правильным именем из ветки Testing
> из какой ветки качать проект?

Нужно добавить к существующему проекту юнит тестирования в файле имя которого указано в issue
> как создавать Unit test отдельный проект или добавить в тот который скачаю?

**Comment by YuriSilenok** [comment]
@Whitetech7417 
В репозитории новый коммит в ветке Testing с существенными изменениями.
рекомендую выполнить команду [git rebase](https://git-scm.com/book/ru/v1/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5)
