### ISSUE TITLE
Разработать сценарии функционального тестирования для формы Дисциплины

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#16]
Разработать сценарии функционального тестирования для Story #3

**Comment by YuriSilenok** [comment]
@DemiKor 
Задача снята так как нет активности более 7 дней.

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F24

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Есть ли сценарии проверяющие это?
> Форма с заголовком дисциплины

**Comment by NastyaFilyushkina** [comment]
А это должен быть автоматизированный тест или мануальный?

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Я сделала.

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
А на меня задачу прикрепить?

**Comment by NastyaFilyushkina** [comment]
А по русски ведь должен заголовок таблицы быть?

**Comment by YuriSilenok** [comment]
На блокировки нужно завести улучшения, с пометкой какую стори оно улучшает

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
А если блокировка из-за бага, например не появление скролла или ,то что таблица не привязана к форме, надо ли заводить улучшения?

**Comment by YuriSilenok** [comment]
Если блокировка из-за бага, то нужно указать ссылко на этот баг в отчете.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
А должна ли по заданию в #3 быть привязана талица к форме?

**Comment by YuriSilenok** [comment]
В этой стори явно не прописано, если такая функциональность не реализована, то стоит поднять улучшение

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/38 
Я уже прописала эти сценарии в баги, потому что не появляются скроллы. Пусть тогда разработчик исправляет?

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F24

**Comment by YuriSilenok** [comment]
Не предусмотрена функция удаления строк. 
нужно написать Improvement-42 с ссылкой соответсвенно

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Надо еще доделать что-то ?

**Comment by YuriSilenok** [comment]
Да, в коментариях в сценариях джолжны быть ссылки на улучшения, я тебе на 2 стори тоже поднял улучшение, поставь, пожалуйста, там тоже ссылки.

**Comment by NastyaFilyushkina** [comment]
Я поставила

**Comment by YuriSilenok** [comment]
Зачтено
