### ISSUE TITLE
Разработать сценарии функционального тестирования для формы Аудитории

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#17]
Разработать сценарии функционального тестирования для Story #4

**Comment by basandpnv** [comment]
[Сценарий.xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2085796/default.xlsx)

**Comment by YuriSilenok** [comment]
Пожалуйста, разместите ваши сценарии в общую [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing)

**Comment by basandpnv** [comment]
Разместила

**Comment by YuriSilenok** [comment]
Зачтено
