### ISSUE TITLE
Разработать сценарии функционального тестирования для формы Группы

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#18]
Разработать сценарии функционального тестирования для Story #5

**Comment by alvhmnv** [comment]
[i№18.xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2081859/i.18.xlsx)

**Comment by YuriSilenok** [comment]
Пожалуйста разместите свои сценарии в [этой](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing) таблице

**Comment by YuriSilenok** [comment]
Не забывайте о том что я не буду проверять задачу пока вы ее не закрепите за мной
