### ISSUE TITLE
Создать форму Добавить преподавателя

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#19]
Форма с заголовком **Добавить преподавателя** должна содержать 
поля:
- Фамилия (Текстовое)
- Имя (Текстовое)
- Отчество (Текстовое)
- Ученая степень (Текстовое)
- Ученое звание (Текстовое)
- Размер педагогического стажа (Числовой от 0 до 60 с шагом 1)
Кнопки:
- Создать
 
Форма **Преподаватели**  в правом нижнем уголу (под таблицей должна иметь кнопку **Добавить**. Кнопка должна быть привязана к правому нижнему углу.

Разрабатывать в ветку issue-19

**Comment by Whitetech7417** [comment]
При нажатии на кнопку : что должно происходить? куда то данные сохранятся которые мы заполнили?

**Comment by YuriSilenok** [comment]
@Whitetech7417 
Если речь идет о кнопке добавить, то должна открыться форма добавления преподавателя.
Если речь идет о кнопке создать, то действий над данными не требуется, просто закройте форму. Пока это пустая болванка. 
По большей части цель этого таска проверить как вы сможете работать с репозиторием.

**Comment by Whitetech7417** [comment]
@YuriSilenok 
Залил в pull request файлы проекта. Либо иx нужно было в саму ветку issue -19 заливать?

**Comment by Whitetech7417** [comment]
@YuriSilenok  залил в ветку. Дальше делать пулреквест в ветку тестировщиков?

**Comment by YuriSilenok** [comment]
@Whitetech7417 Да

**Comment by Whitetech7417** [comment]
@YuriSilenok  Обновил ветку issue-19. Дописал там ручной тест(я так понимаю это тест который мы делаем прямо из самой программы) без понятия что вообще стоило мне делать , так как форма может принять в один момент только данные один раз. Ну я сделал чтобы все текст боксы заполнялись определенными данными когда запускается форма. Плюс начал писать сценарий https://docs.google.com/spreadsheets/d/1DcjjjTjMone55xROsFI4yg7gYtupY4L3dXp6sxNOYBA/edit#gid=0. Подскажите что еще нужно делать со сценарием ? Ведь кнопка "Создать" она вообще ничего не должна делать , как вы сказали , но какие то сценарии все же надо написать?

**Comment by YuriSilenok** [comment]
@Whitetech7417 Ни о каких тестах речи не шло. То что вы видете в конце дискрипшена стори (место где можно ставить галочки), это техническая информация. Никакие сценарии Вам писать не нужно, пока не будет поставлена на это задача в отдельном таске.

**Comment by YuriSilenok** [comment]
Я так и не увидел что вы ссылались в пулреквесте на эту стори.

**Comment by Whitetech7417** [comment]
@YuriSilenok  xорошо, я понял , а что мне нужно описать в пулл реквесте для разработчиков?

**Comment by YuriSilenok** [comment]
Нужно в пулреквесте в описании поставить решетку и номер стори, после решетки будут подсказки.
В твоем случае это будет решетка 19, если все правльно сделаешь, то в стори в комментариях появится запись что на эту стори ссылается такой-то пулреквест.

**Comment by Whitetech7417** [comment]
@YuriSilenok 
Что мне дальше делать?  готов продолжить  работу по разработке.
