### ISSUE TITLE
Неправильная сортировка в столбце "Размер педагогического стажа" таблицы Преподаватели

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#26]
Затрагивает #2 
Подготовлена ветка issue-26

**Шаги:**
1. Нажать на выпадающее меню "Справочники"
2. Из выпадающего меню нажать "Преподаватели"
3. Ввести  в колонку  "Размер педагогического стажа" числа: в 1 строке "2", во второй строке "1 ", в третей строке "12"
4. Нажать на заголовок столбца "Размер педагогического стажа", чтобы сортировка производилась по возрастанию.
**Фактический результат:** 
![image](https://user-images.githubusercontent.com/37622382/40991152-88b8d446-68fb-11e8-847b-1d9425ad05a1.png)
**Ожидаемый результат:** строки отсортированы в порядке возрастания значений в ячейках столбца "Размер педагогического стажа"

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina Посмотри этот баг, это будет для тебя образцом по оформлению. В нем должно быть только самое необходимое.

**Comment by YuriSilenok** [comment]
@blinker44 
Когда исправите, сначало вы должны выполнить пул реквест, заасанить на меня, если с ним все хорошо, то баг перевестить на того кто его создавал для проверки, как только он будет закрыт, зачту работу. Не забудте указать в пул реквесте ссылку на этот баг.

**Comment by YuriSilenok** [comment]
@blinker44 
Есть ли у Вас идеи как можно поправить этот баг?

**Comment by blinker44** [comment]
@YuriSilenok 
Пока нет, как и с #40 
Только если лочить всю таблицу и программно сортировать вызывая свою сортировку через кнопку

**Comment by YuriSilenok** [comment]
@blinker44 
Это разрабатываемое ПО реализует шаблон MVC.
Вам необходимо использовать метод который бы возвращал уже отсортированные в нужном порядке данные.
Для этого вы бы могли использовать #54, проблема в том, что эту стори невозможно начать, пока не будет реализована стори #33.
Если у Вас есть возможность обратиться к исполнителю таска #33 @Natalia666503, то напомните ей, что по этой стори уже не было давно активности и сообщите что если нет активности по таску 7 дней, таск будет передан другому человеку.
Вероятно Вам.

**Comment by YuriSilenok** [comment]
@blinker44 
Назначаю Вам стори #54 
Реализовав ее, вы сможете и исправить ошибку сортировки, если непонятно как это связано, задайте вопрос.

**Comment by blinker44** [comment]
@YuriSilenok 
Что мне в итоге делать? Для педагогического стажа нужна сортировке как для int чисел, мне программно её реализовывать? Если да, то использую принцип из соседних моих тасков. Просто буду использовать не Compare, а обычные операции сравнения

**Comment by blinker44** [comment]
@YuriSilenok 
Понял.
Тогда мне также следует изменить часть кода связанную с сравнением.

**Comment by YuriSilenok** [comment]
не знаю о каком конкретном месте вы говорите, но можете поэксперементировать

**Comment by blinker44** [comment]
@YuriSilenok 
А что мне делать, если в столбец, допустим, занесены числа, но одно или несколько из них содержит символ не являющийся цифрой? Мне это проверять, или это не в моей области ответственности
На данный момент подправил сортировку под числа в #40 , в следствие чего такой вопрос и появился. Я не учитываю возможное наличие "нецифр"

**Comment by YuriSilenok** [comment]
@blinker44 
Так, кажется вы не в курсе жизненного цикла бага.
1. Он поднимается тестировщиком (иногда разработчиком) на разработчика (чаще старшего разработчика)
2. На баг создается ветка и назначается исполнителью
3. После исполнения поднимается пулреквест
4. Если пул реквест одобрен и произошел мерж, только тогда таск с багом назначается тестировщику.
5. и уже после проверки тестировщиком баг закрывается или отправляется на доработку.

**Comment by YuriSilenok** [comment]
Ветку пересоздал

**Comment by YuriSilenok** [comment]
задача не актуальная.
