### ISSUE TITLE
(Дубликат) Происходит неправильная сортировка по столбцу "Размер педагогического стажа" по убыванию

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#27]
Неправильная сортировка по столбцу "Размер педагогического стажа" по убыванию при наличии многозначных чисел в ячейках этого столбца.
Сценарий:
1. Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Ввести  в колонку  "Размер педагогического стажа" числа: в 1 строке "1",во  второй строке"2 ",в третей строке "12"
4.Нажать на заголовок столбца "Размер педагогического стажа",чтобы сортировка производилась по убыванию.
Фактический результат:
![image](https://user-images.githubusercontent.com/37622382/40991075-56d49c12-68fb-11e8-91e9-928ddb7f174a.png)
Ожидаемый результат: строки отсортированы в порядке убывания значений в ячейках столбца "Размер педагогического стажа"
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/2

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Привыкайте оперировать двумя понятиями, которые нельзя модицифировать.
Ожидаемый результат (Expected result)
Файтический результат (Actual result)

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Этот баг является дубликатом к багу #26 Так как суть бага заключается что для числовых значений выполняется посимвольная сортировка.
Баг #26 будет переименован в **Неправильная сортировка в столбце "Размер педагогического стажа" таблицы преподаватели**
