### ISSUE TITLE
Создать форму Дисциплины

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#3]
Форма с заголовком дисциплины должна содержать в себе таблицу со стобцами
*  Наименование
*  Код - смотрите учебный план

Столбцы должны быть сортируемыми.
Таблица должна иметь вертикальную и горизонтальную прокрутку в случае нехватки места для формы

Разрабатывать в ветку issue-3

**Comment by blinker44** [comment]
Готово.

**Comment by YuriSilenok** [comment]
@blinker44 мерж не состоялся, у вас дубликаты в меню. Но думаю вы и так получили на почту комментарий об этой из пулреквеста.

**Comment by blinker44** [comment]
Исправил.

**Comment by YuriSilenok** [comment]
@blinker44 
Если вы не повесите на меня задачу, я не узнаю о том что ее нужно проверить и как следствие зачесть.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@blinker44 
Вы реализовывали этот функционал?
> Таблица должна иметь вертикальную и горизонтальную прокрутку в случае нехватки места для формы
