### ISSUE TITLE
Создать контроллер для объекта Преподаватель

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#33]
Затрагивает #2, #19
Модель(класс CTeacher) создается отдельным файлом (CTeacher.cs) в проекте(библиотеке) решения.
Реализовать в ветку issue-33
Это фрагмент диаграммы классов в нотации UML.
Реализовать класс с полями и методами (тело которых не содержит кода)
![image](https://user-images.githubusercontent.com/14871471/41064114-41cb9d0a-69e3-11e8-80dd-f212939092e6.png)
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)на текущую версию диаграммы классов.

**Comment by YuriSilenok** [comment]
@Natalia666503 
Есть ли у Вас вопросы по этому таску?

**Comment by Natalia666503** [comment]
@YuriSilenok 
При создании листа объектов класса MTeacher он не видит этого класса

**Comment by YuriSilenok** [comment]
@Natalia666503 
Что нужно проверить
- Необходимый класс имеет атрибут **public**
- файл с контроллером создается в библиотеке, там же где и вызываемый класс.

**Comment by Natalia666503** [comment]
все равно не видит. в ветке issue-30 все есть, а в моей 33 нет  воскресенье, 10 июня 2018г., 20:59 +03:00 от Yuri Silenok  notifications@github.com :

**Comment by YuriSilenok** [comment]
@Natalia666503 
Сделал для вашей ветки git rebase Testing
Вам необходимо выполнить команду git pull чтобы получить эти изменения
