### ISSUE TITLE
Не появляется скролл для таблицы Дисципины

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#38]
Затрагивает #3 
Подготовлена ветка issue-38
Сценарий №1.
**Шаги**:
1. Нажать на выпадающее меню "Справочники"
2. Из выпадающего меню нажать "Дисциплины"
3. Ввести в любую ячейку такое значение, чтобы ячейка выходила за предел формы.
4. Нажать Enter
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41118659-40a7f0f2-6a99-11e8-8184-455447b7d487.png)
**Ожидаемый результат:** Длинное значение в ячейке с  видно полностью, появление горизонтального скролла.
Сценарий №2.
**Шаги**:
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Дисциплины"
3.Уменьшить форму, чтобы форма была меньше ширины таблицы.
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41118910-01166274-6a9a-11e8-87d9-40504d9df643.png)
**Ожидаемый результат:** Появление горизонтального скролла.
Сценарий №3.
**Шаги**:
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Дисциплины"
3.Выбрать ячейку.
4.Ввести короткое значение ячейки.
5.Нажать Enter
6.Выбрать эту же ячейку.
7.Изменить значение на более длинное .
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41118977-3d3f4f72-6a9a-11e8-958b-06ae959d17fa.png)
**Ожидаемый результат:** Длинное значение в ячейке с  видно полностью, появление горизонтального скролла.
Сценарий №4.
**Шаги**:
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Дисциплины"
3.Ввести в первые три строки в столбец "Наименование" любые значения
3.1.   Ввести значение в ячейку
3.2.    Нажать Enter
3.3    Повторить с 3. по 3.3 три раза
4.Уменьшить форму, чтобы форма была меньше длинны таблицы
https://guides.github.com/features/mastering-markdown/Уменьшить форму, чтобы форма была меньше длинны таблицы
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41119220-f731417e-6a9a-11e8-9a39-37c8831e1388.png)
**Ожидаемый результат:** Появление вертикального скролла.

**Comment by blinker44** [comment]
Исправлено. Фиксация сделана

**Comment by YuriSilenok** [comment]
@blinker44 
- Вы создали пулреквест в котором сослались на этот баг?

**Comment by YuriSilenok** [comment]
@blinker44 Прошло 7 дней с последней вашей активности, если Вы не выйдете на связь по этому таску, таск будет с Вас снят.

**Comment by NastyaFilyushkina** [comment]
Я нахожусь в ветке 38, но исправлений сценариев 2 и 4 не вижу
![image](https://user-images.githubusercontent.com/37622382/41738904-18c8885e-759c-11e8-8984-7a0e8a1773c5.png)
![image](https://user-images.githubusercontent.com/37622382/41738916-21c39c5a-759c-11e8-8e23-7d00d0def7e3.png)
Я точно в ветке, в которой нужно?
