### ISSUE TITLE
Неправильная сортировка по столбцу"Код"в таблице"Дисциплины"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#40]
Затрагивает #3
Подготовлена ветка issue-40
**Шаги:**
1. Нажать на выпадающее меню "Справочники"
2. Из выпадающего меню нажать "Дисциплины"
3. Ввести в первые шесть строк в столбец "Код"
1 строка - столбец Код "Б.1.Б.31"
2 строка - столбец Код "А.14.С.14"
3 строка - столбец Код "А.2.С.14"
4 строка - столбец Код "Б.1.Б.4"
5 строка - столбец Код"А.1.Б.2"
6 строка - столбец Код"С.1.А.10"
4. Нажать на заголовок столбца "Код",чтобы сортировка происходила в алфавитном порядке(буквы) по возрастанию(числа).
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41120659-d3b6db10-6a9e-11e8-9cdd-561842e3ae5b.png)
**Ожидаемый результат:** строки отсортированы в порядке возрастания(чисел) и алфавитном порядке(буквы).

**Comment by YuriSilenok** [comment]
@blinker44 
По этому таску у Вас не было активности более 7 дней, завтра если активности не будет, таск будет снят.

**Comment by blinker44** [comment]
@YuriSilenok 
Реализую в течение ближайших дней
Если возникнут вопросы, я к вам обращусь

**Comment by YuriSilenok** [comment]
Здесь можете не отписывать, я вижу все по пуллреквесту.

**Comment by YuriSilenok** [comment]
Комбинированное поле...я могу снать это задае с Вас, так как оно слишком объемное.

**Comment by blinker44** [comment]
@YuriSilenok 
То есть, нужно учитывать значения после точек?
А код действительно может выглядеть так, как в тесте? Код обычно только числовой
Если снимите задание, то таск за мной пропадет?

**Comment by YuriSilenok** [comment]
Будет зачтен, так как не по твоей вине.

**Comment by blinker44** [comment]
@YuriSilenok 
Я не могу оценить свою работу. Если есть те, кто справился бы лучше, то снимайте пожалуй.
Могу продолжить, но должен знать что конкретно от меня сейчас нужно
Commit'ы в #26 и этом тасках пушнул

**Comment by YuriSilenok** [comment]
Баг недействителен, так как код должен воспринимать как строка целиком.
