### ISSUE TITLE
Неверный заголовок таблицы"Дисциплины"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#41]
Затрагивает #3 
Подготовлена ветка issue-41
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Дисциплины"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41121016-ee2d8c5e-6a9f-11e8-892d-ff41361003a5.png)
**Ожидаемый результат:** таблица имеет заголовок "Дисциплины"

**Comment by blinker44** [comment]
Исправлено. Фиксация сделана

**Comment by YuriSilenok** [comment]
@blinker44 
Вы создали пулреквест в котором указали что он затрагивает этот баг?

**Comment by blinker44** [comment]
@YuriSilenok 
Всё также в ветку testing?

**Comment by YuriSilenok** [comment]
Да, story, bug, improvment мержутся в ветку Testing

**Comment by blinker44** [comment]
@YuriSilenok 
Есть проблема:
![image](https://user-images.githubusercontent.com/38395077/41319654-401b25ae-6ea5-11e8-8c55-b88d082bd4a0.png)

**Comment by YuriSilenok** [comment]
@blinker44 
Есть ли среди ниже перечисленных команд которой вы не пользовались?
git pull
git checkout issue-41
git add .
git commit -m "my comment"
git push

**Comment by YuriSilenok** [comment]
@blinker44 баги перекидываются на тестера только тогда мерж состоялся, а не когда он только открыт. Обычно после мержа стараюсь сам перекидывать баги на автора, но если я забуду, можете сделать это самостоятельно.
