### ISSUE TITLE
Функция удаления строки для формы "Дисциплины"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#42]
Внизу формы "Дисциплины" должна быть недоступная кнопка "Удалить".При выделении строки она становится доступной. При нажатии на кнопку должна удалятся выделенная строка и сохранятся выбранная сортировка.

Разрабатывать в ветку issue-42

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina А для какой формы?

**Comment by alvhmnv** [comment]
Обновил файлы.

**Comment by YuriSilenok** [comment]
Да, все верно, в дальнейшем эта функция будет отключена, не забывайте с себя снимать задачи которыми не занимаетесь.

**Comment by YuriSilenok** [comment]
Я ожидаю от Вас запрос на пул реквест на слияние веток.
В котором должна быть ссылка на этот таск.

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Выполнить повторное тестирование.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
В таблице есть сценарий про удаление неотображаемых строк, наверное он совсем не нужен, его удалить или пустые строки просто будут удалятся по кнопке и тест пройден? или нужна еще кнопка для удаления всех неотображаемых строк?

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Что значит не отображаемые строки?
Если они не отображаются, то их невозможно выделить.
Если это пустые строки (у которых значения в ячейке пустая строка), то таких значений не должно быть, а это формирует ограничение на вводимое значение. Думаю пора вводить форму изменения дисциплины, что бы не происходило через таблицу.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Тогда я удалю этот сценарий?

**Comment by YuriSilenok** [comment]
Да.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Мне закрыть баг, оставив на себе?

**Comment by YuriSilenok** [comment]
Да
