### ISSUE TITLE
Функция удаления строки для формы "Преподаватели"

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#43]
Внизу формы "Преподаватели" должна быть недоступная кнопка "Удалить".При выделении строки она становится доступной. При нажатии на кнопку должна удаляться выделенная строка и сохранятся выбранная сортировка.

Разрабатывать в ветку issue-43

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina Завел этот таск, не заведи дубликат

**Comment by Whitetech7417** [comment]
@YuriSilenok 

Обновил файлы. Сделал pull request в ветку тестировщиков.

**Comment by YuriSilenok** [comment]
Таск на улучшение закрепляйте на себя, пока не состоится мерж по поднятому пулреквесту. После этого таск необходимо перекинуть на тестировщика NastyaFilyushkina
