### ISSUE TITLE
Разработать сценарии функционального тестирования для формы Добавить преподавателя

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#46]
Затрагивает стори #19 
[Таблица](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing) сцеанриев

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Текстовое поле это просто поле, в которое можно вводить и буквы и цифры?(На форме в поле я могу вводить и то и то)
Например Фамилия (Текстовое). Если да ,то завести улучшение чтобы можно было вводить только буквы в тестовые поля?

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F75

**Comment by YuriSilenok** [comment]
Я ожидаю что текстовые поля должны игнорировать все символы кроме тех которые относятся к алфавитным (Русский и Английски, оба регистра) и тире (составные имена типа Анна-Мария)
> Текстовое поле это просто поле, в которое можно вводить и буквы и цифры?(На форме в поле я могу вводить и то и то)

Да, нужно поднять улучшение.
>Например Фамилия (Текстовое). Если да ,то завести улучшение чтобы можно было вводить только буквы в тестовые поля?

Да, ты уцепилась за золотую жилу под названием верстка. Они не всегда прописываются в стори, но их тоже тестят. Если ты видишь глазами что интерфейс неудобный, это тоже можно поднять как улучшение.
>При изменении размера формы "Добавить преподавателя" одно поле к ней не привязано и не появляются скроллы, это нужно прописывать в таблице если этого нет в #19 ? И это в улучшения?

Зачтено.

**Comment by YuriSilenok** [comment]
И Поле со стажем должно быть таким. 
![image](https://user-images.githubusercontent.com/14871471/41196277-fb7b9652-6c44-11e8-9860-4d8fd1ac868b.png)

**Comment by NastyaFilyushkina** [comment]
Приведите ,пожалуйста, пример негативного теста. Это на символы вводимые в строки?

**Comment by YuriSilenok** [comment]
Позитивный тест, мы заполняем все необходимые поля и проверяем что на корректный данных создаётся нечто. В негативном тесте мы по сути проверяем все ограничения в отдельности, то есть мы можем по очередно вводить запрещённые символы. Особенность нашей гуи в том что эти символы должны игнорироваться и в общем случае можно составить один тест на попытку ввода всех текстовых полей с символами цифр в перемешку, другой будет пытаться вводить знаки припенания и т.д.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Проблема в понимании Test Data. [Описание ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable#test-data)каждого из столбцов.
То что вводится в поля описывается в самих шагах.
Тест дата в вашей строри вообще не требуется

**Comment by YuriSilenok** [comment]
Мы предполагаем что то что мы вводим в текстовые поля могут автоматически изменяться в процессе ввода, это значит что каждое из полей в отдельности может быть изменено там где и не должно быть. Этим я хочу сказать, что ввод значение в текстовое поле это отдельный шаг, а ожидаемым результатом для этого шага будет конкретное значение. Представьте что будет функция в поле фамилия которая первую букву будет переводить в верхний регистр.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Я правильно поняла что мне надо сделать?
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=A92

**Comment by YuriSilenok** [comment]
Да, там все готово?

**Comment by YuriSilenok** [comment]
Да, там все готово?

**Comment by NastyaFilyushkina** [comment]
ну в сценариях да, сейчас я только улучшения заведу и все готово.
