### ISSUE TITLE
Ручное тестирование формы Добавить преподавателя

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#47]
Затрагивает стори #19
[Таблица ](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F76)сценариев

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F76

**Comment by YuriSilenok** [comment]
Зачтено
