### ISSUE TITLE
Неверный заголовок таблицы "Добавить преподавателя"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#49]
Затрагивает #19 
Подготовлена ветка issue-49
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Создать"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41193910-17676928-6c1c-11e8-9b9d-ee68256cac6d.png)
**Ожидаемый результат:** таблица имеет заголовок "Добавить преподавателя"

**Comment by Whitetech7417** [comment]
@YuriSilenok Bug исправил, перезалил в ветку issue-19.
Сделал pull request на тестирование.

**Comment by YuriSilenok** [comment]
@Whitetech7417 Ваши ошибки:
- Исправлять нужно было в ветке issue-49, так как баг именно этот таск описывает.
- Вы написали что исправили баг, тогда почему он все еще на вас весит?
- Вы создали пул реквест на исправление этого бага, но на баг не сослались!!!!

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Проверить исправление бага, если да, закрыть оставив его на себе.
