### ISSUE TITLE
Создать форму Группы

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#5]
Форма с заголовком Группы должна содержать в себе таблицу со стобцами
*  Шифр
*  Численность

Столбцы должны быть сортируемыми.
Таблица должна иметь вертикальную и горизонтальную прокрутку в случае нехватки места для формы

Разрабатывать в ветку issue-5

**Comment by YuriSilenok** [comment]
@Jenackl Теперь ошибки которые которые были Вами допущены.

- Вы не заасанили на себя таск, теперь думаю я сам буду асанить таски сам.
- Таск нужно было разрабатывать в определнную ветку, о ней написано в описании таска
- После выполнения нужно было сделать запрос на слияние веток.

**Comment by YuriSilenok** [comment]
@Jenackl 
Этот таск с Вас снят, так как Вы не проявляете активность по этому таску более недели.

**Comment by TanyaMalis** [comment]
[TimetableOfClasses.zip](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2065012/TimetableOfClasses.zip)

**Comment by YuriSilenok** [comment]
@TanyaMalis 
Были ли реализованы эти функциональности?
>  Форма с заголовком Группы

>  Таблица должна иметь вертикальную и горизонтальную прокрутку в случае нехватки места для формы

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Да, только форма c заголовком "Groups"

**Comment by YuriSilenok** [comment]
Это плохо, задачи нужно реализовывать в точности.
