### ISSUE TITLE
Реализация метода CTeacher.GetData():string[,]

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#53]
Затрагивает #33
Реализовывать в ветку issue-53
Метод вернет значения из существующих объектов MTeacher в виде двумерного массива составленного из teacherList

**Comment by YuriSilenok** [comment]
@TanyaMalis 
Вы забыли на меня этот таск перекинуть

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Вы сказали, что код покажете

**Comment by YuriSilenok** [comment]
@TanyaMalis 
Изменения в коде смотреть [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/86/files)
