### ISSUE TITLE
Реализация метода CTeacher.GetData(columnName:string, order:bool):string[,]

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#54]
Затрагивает #33
Реализовывать в ветку issue-54
Метод вернет значения из существующих объектов MTeacher в виде двумерного сортированного по столбцам массива составленного из teacherList
Значения входных параметров:
- columnName:string - Имя сортируемого столбца
- order:bool - истина в прямом порядке, лож в обратном порядке

**Comment by blinker44** [comment]
Фиксация сделана. Проблема из комментария к таску #41  осталась

**Comment by YuriSilenok** [comment]
@blinker44 Вы собираетесь доделывать таск?

**Comment by YuriSilenok** [comment]
@blinker44 
Через 3 дня задача с Вас будет снята, проявите активность
