### ISSUE TITLE
При вводе в поля формы "Добавить преподавателя" некорректные символы не игнорируются

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#56]
Затрагивает #19 
Подготовлена ветка issue-56
Сценарий №1
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"абв"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204559-b2691264-6cee-11e8-825d-d687c50c808b.png)
**Ожидаемый результат:** Строка пустая
Сценарий №2
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"1000"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204579-f8c82164-6cee-11e8-9b02-58a1a0ce0125.png)
**Ожидаемый результат:** Размер педагогического стажа"10"
Сценарий №3
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"10,5"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204581-09b2585a-6cef-11e8-8aa9-3579fbdff5c8.png)
**Ожидаемый результат:** Размер педагогического стажа"10"
Сценарий №4
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"10.5"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204584-1604707a-6cef-11e8-80db-007570b11e98.png)
**Ожидаемый результат:** Размер педагогического стажа"10"
Сценарий №5
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"-6"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204596-3bacc9da-6cef-11e8-9b95-495c86aa6c82.png)
**Ожидаемый результат:** Размер педагогического стажа"6"
Сценарий №6
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"000"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204603-6cda93e8-6cef-11e8-8eb4-dbf31bf78b43.png)
**Ожидаемый результат:** Размер педагогического стажа"0"
Сценарий №7
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Размер педагогического стажа"!"№;%:?*()/=*-+9"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204645-d4fb5e08-6cef-11e8-96d8-e7075761e9a0.png)
**Ожидаемый результат:** Размер педагогического стажа"9"
Сценарий №8
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Фамилия "Ивано1в"
Имя "Иван3"
Отчество "Ив54анович"
Ученая степень"До54ктор наук"
Ученое звание"Про3фессор"
Размер педагогического стажа"20"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204666-3b519370-6cf0-11e8-91d2-fab2d6d9e70c.png)
**Ожидаемый результат:** 
Фамилия "Иванов"
Имя "Иван"
Отчество "Иванович"
Ученая степень"Доктор наук"
Ученое звание"Профессор"
Размер педагогического стажа"20"
Сценарий №9
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Фамилия "Ив%ан,ов"
Имя "Ива.н"
Отчество "Ив№ано:вич"
Ученая степень";Докт?ор на()ук"
Ученое звание"Пр-офе+сс!ор"
Размер педагогического стажа"20"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204682-98fbfb14-6cf0-11e8-808b-5667d76f7f79.png)
**Ожидаемый результат:** 
Фамилия "Иванов"
Имя "Иван"
Отчество "Иванович"
Ученая степень"Доктор наук"
Ученое звание"Профессор"
Размер педагогического стажа"20"
Сценарий №10
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Фамилия "Иванов--Васильев"
Имя "Иван--Анатолий"
Отчество "Иванович--Иванович"
Ученая степень"Доктор наук"
Ученое звание"Профессор"
Размер педагогического стажа"20"
**Фактический результат:**
![image](https://user-images.githubusercontent.com/37622382/41204733-2d175e74-6cf1-11e8-88cb-db393447fe1e.png)
**Ожидаемый результат:** 
Фамилия "Иванов-Васильев"
Имя "Иван-Анатолий"
Отчество "Иванович-Иванович"
Ученая степень"Доктор наук"
Ученое звание"Профессор"
Размер педагогического стажа"20"

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Не очень поняла, какой таск делать - 72 или 56

**Comment by alvhmnv** [comment]
Я же сделал и 56 и 72

**Comment by NastyaFilyushkina** [comment]
но на меня то не перекинули для проверки исправления.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Я нашла еще один сценарий бага, мне заводить новый ? И некорректные символы не игнорируются, они просто удаляются при переходе к другой строке. Так и задумывалось или надо сделать чтобы они совсем не могли вводится?

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Баги заводи все что посчитаешь нужными на меня, там их разгребу.
Предполагалось что некоррекнты символы должны игнорироваться уже в процессе ввода данных, а не при уходе фокуса.

@alvhmnv 
Тут я действительно накосячил, не посмотрел что это баг.
> окей, я просто думал все, что сделали на Юрия Викторовича перекидывать для проверки, так и сделал и он потом закрыл таск

**Comment by alvhmnv** [comment]
@YuriSilenok, я неправильно понял задание значит насчёт игнорирования сразу 
Готов исправить

**Comment by YuriSilenok** [comment]
@alvhmnv По возможности он к вам вернется. Есть ли у Вас задачи?

**Comment by alvhmnv** [comment]
@YuriSilenok, да, у меня сейчас задача с автоматизацией тестирования

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Что делать с этим таском? Его надо переделать чтобы символы игнорировались сразу, а не после перехода к другому полю.

**Comment by NastyaFilyushkina** [comment]
Таск надо переделать, чтобы символы игнорировались сразу при вводе и новый баг 
Сценарий №11
Шаги:
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Преподаватели"
3.Нажать на кнопку "Добавить преподавателя"
4.Ввести в поля заданные значения.
Фамилия "Иванов-"
Имя "Иван-"
Отчество "Иванович-"
Фактический результат:
![image](https://user-images.githubusercontent.com/37622382/41686537-1bd56d1e-74ed-11e8-8b0c-ad05fa1becd8.png)
Ожидаемый результат:
Фамилия "Иванов"
Имя "Иван"
Отчество "Иванович"

**Comment by YuriSilenok** [comment]
@alvhmnv Игнорирование одного символа? Для примера в таблице Unicode всего 65536 символов, из них должны вводиться только русские буквы верхнего и нижнего регистра, Вы будете делать ~65000 заглушек? Рекомендую ознакомиться с [этим ](https://msdn.microsoft.com/ru-ru/library/system.char_methods(v=vs.110).aspx) материалом особенно обратите на IsLetter(Char).

**Comment by alvhmnv** [comment]
@YuriSilenok не понимаю, как тогда, например, для такой обработки игнорировать ещё и англ алфавит не прибегая опять к тем же условиям, чтобы были раньше у меня

if (!Char.IsLetter(e.KeyChar)  && e.KeyChar != Convert.ToChar(8) && e.KeyChar != Convert.ToChar(45))
e.Handled = true;

**Comment by YuriSilenok** [comment]
Вы описывали при помощи регулярок, в этом случае это правильно. я думаю Вам стоит продолжить эту тему, только постараться сделать не несколько регулярок, а написать одно условие соответствующее правилу. Я думаю вам поможет в этом этот сайт https://regex101.com/ 
Если возникнут проблемы с описанием шаблона, пишите, разберемся.

**Comment by alvhmnv** [comment]
Мне не приходит в голову, как можно все в одно сделать, ведь для разных полей разные символы должны быть, где-то пробел, а где то дефис, 
про повторяющийся код вы так же написали в пулл реквесте, объединить все методы я могу только разве что с использованием тегов для определенных полей, но код опять же повторяться будет, потому что символы разные должны быть

**Comment by YuriSilenok** [comment]
Не актуально
