### ISSUE TITLE
Масштабирование формы "Добавить преподавателя"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#58]
Затрагивает #19 
Подготовлена ветка issue-58
При уменьшении/увеличении формы "Добавить преподавателя" элементы должны находится на своих местах и уменьшатся/увеличиваться вместе с формой. Если длинна формы меньше 453, и/или ширина меньше 699 , тогда должны появляться вертикальные и/или горизонтальные скроллы.

**Comment by basandpnv** [comment]
Как я понимаю разрабатывать надо в ветку issue-58, но она не создана

**Comment by YuriSilenok** [comment]
@basandpnv 
Действительно не было, странно, теперь точно есть.
