### ISSUE TITLE
Неверный заголовок таблицы "Аудитории"

### ISSUE THREAD

**Issue by basandpnv** [Students-of-the-city-of-Kostroma/Student-timetable-old#59]
Затрагивает Story #4, Scenario #17 
Подготовлена ветка issue-59
Шаги: 
1. Нажать на выпадающее меню "Справочники" 
2.Из выпадающего меню нажать "Аудитории" 
Фактический результат: 
![2](https://user-images.githubusercontent.com/38126706/41220490-3a393ad6-6d6a-11e8-973d-6668e20dfa35.jpg)
Ожидаемый результат: таблица имеет заголовок "Аудитории"

**Comment by YuriSilenok** [comment]
@basandpnv 
Проверить что баг исправлен
