### ISSUE TITLE
Неправильная сортировка по столбцу "Вместительность" в таблице "Аудитории"

### ISSUE THREAD

**Issue by basandpnv** [Students-of-the-city-of-Kostroma/Student-timetable-old#60]
Затрагивает Story #4, Scenario #17 
Тестовый сценарий № 16
Шаги: 
1.Нажать на выпадающее меню "Справочники" 
2.Выбрать - "Аудитории" 
3.Ввести в первые 3 строки в столбец "Вместительность" заданные значения: 
   1 строка - столбец Вместительность "40" 
   2 строка - столбец Вместительность "25" 
   3 строка - столбец Вместительность "100"   
4.Нажать на заголовок столбца "Вместительность" 
Фактический результат: 
![3](https://user-images.githubusercontent.com/38126706/41221127-f271eafc-6d6b-11e8-8c18-8264834ca330.jpg)
Ожидаемый результат: строки отсортированы в порядке возрастания 
Тестовый сценарий № 17
Шаги: 
1.Нажать на выпадающее меню "Справочники" 
2.Выбрать - "Аудитории" 
3.Ввести в первые 3 строки в столбец "Вместительность" заданные значения: 
   1 строка - столбец Вместительность "40" 
   2 строка - столбец Вместительность "25" 
   3 строка - столбец Вместительность "100"   
4.Нажать на заголовок столбца "Вместительность" 
Фактический результат: 
![4](https://user-images.githubusercontent.com/38126706/41221340-87242b56-6d6c-11e8-918f-58f32e5f9a6b.jpg)
Ожидаемый результат: строки отсортированы в порядке убывания

**Comment by YuriSilenok** [comment]
Для исправления бага подготавливается функционал #121
