### ISSUE TITLE
Не сохраняется сортировка при добавлении новой строки в столбце "Вместительность" таблицы "Аудитории"

### ISSUE THREAD

**Issue by basandpnv** [Students-of-the-city-of-Kostroma/Student-timetable-old#61]
Затрагивает Story #4, Scenario #17 
Шаги: 
1. Нажать на выпадающее меню "Справочники" 
2. Выбрать - "Аудитории" 
3. Ввести в первые 3 строки любые данные значения в каждую ячейку 
4. Нажать на заголовок столбца "Номер" 
5. Заполнить еще одну строку произвольными данными 
6. Нажать Enter 
Фактический результат: 
![5](https://user-images.githubusercontent.com/38126706/41221623-531305fc-6d6d-11e8-9b60-0f4c86367243.jpg)
Ожидаемый результат: новая строка встала на свое место

**Comment by YuriSilenok** [comment]
Первоначальное получение данных #121 и сортировка данных #128 должны быть получены при помощи контроллера.

**Comment by YuriSilenok** [comment]
Не актуально
