### ISSUE TITLE
Ручное тестирование формы Группы

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#63]
Для стори #5 сценарии #18

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Я протестировала сценарии, но  ,по-моему мнению, сценарии неполные, потому что я уже тестировала такие формы и знаю что сортировка там нарушена, но в сценариях тесты содержат такие данные, при которых эти ситуации не возникнут
Например вот это
 1 строка - столбец Численность ""25"
 2 строка - столбец Численность ""19"
 3 строка - столбец Численность ""22"
если добавить в ячейку одну цифру или многозначное число, то все будет плохо
![image](https://user-images.githubusercontent.com/37622382/41249194-158fd774-6dbc-11e8-9bdc-968ab1f4004a.png)

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Сформировал специально для этого небольшой таск.
> Наверное нужно поправить сценарии.

**Comment by YuriSilenok** [comment]
Зачтено
