### ISSUE TITLE
Не сохраняется сортировка при добавлении новой строки в таблицу формы "Группы"

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#67]
Затрагивает Story #5 
Подготовлена ветка issue-67
**Шаги:**
1.Нажать на выпадающее меню "Справочники"
2.Из выпадающего меню нажать "Группы"
3.Ввести в первые 2 строки любые значения в каждую ячейку столбца "Численность"
4.Нажать на заголовок столбца "Численность"
5.Заполнить еще одну строку произвольными данными
6.Нажать Enter
Фактический **результат:**
![image](https://user-images.githubusercontent.com/37622382/41251237-025cf5c8-6dc2-11e8-8ec9-ad14e6998d33.png)
**Ожидаемый результат:**
 новая строка встала на свое место

**Comment by Whitetech7417** [comment]
@YuriSilenok после исправления залить в ветку issue 67?

**Comment by YuriSilenok** [comment]
- если ветки нет, создать ветку из тестовой
- на ПК переключиться на созданную ветку
- вы ней изменить код
- проиндексировать, закомитить, выгрузить изменения
- сделать запрос на пулреквест (желательно с тем же названием что и таск)
