### ISSUE TITLE
Не появляется скролл в таблице "Группы" при изменении размеров формы

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#68]
Затрагивает #5 
Подготовлена ветка issue-68
Сценарий №1.
Шаги:
 1.Нажать на выпадающее меню "Справочники"
 2.Выбрать - "Группы"
 3.Уменьшить форму, чтобы форма была меньше ширины таблицы.
Фактический результат:
изображение
![image](https://user-images.githubusercontent.com/37622382/41251844-deb11166-6dc3-11e8-97ed-ff552a6bea78.png)
Ожидаемый результат: Появление горизонтального скролла.
Сценарий №2.
Шаги:
 1.Нажать на выпадающее меню "Справочники"
 2.Выбрать - "Группы"
 3.Уменьшить форму, чтобы форма была меньше длинны таблицы.
Фактический результат:
изображение
![image](https://user-images.githubusercontent.com/37622382/41251888-0dbe7e44-6dc4-11e8-97da-0ddf193c5838.png)
Ожидаемый результат: Появление вертикального скролла.
Сценарий №3.
Шаги:
 1.Нажать на выпадающее меню "Справочники"
 2.Выбрать - "Группы"
 3.Увеличить форму, чтобы форма была больше длинны таблицы.
Фактический результат:
![image](https://user-images.githubusercontent.com/37622382/41251948-4836f36c-6dc4-11e8-8ff4-89c996c2085b.png)
Ожидаемый результат: Появление вертикального скролла.

**Comment by Natalia666503** [comment]
@YuriSilenok Данная ветка находится в master, а не в Testing. В ней нет нужной мне формы.

**Comment by YuriSilenok** [comment]
Да, действительно, я ее удалил и пересоздал

**Comment by Whitetech7417** [comment]
В какую ветку мне залить исправленную версию? @YuriSilenok

**Comment by YuriSilenok** [comment]
@Whitetech7417 
Хм, как не странно, но этот баг уже поправлен и даже с мержен в ветку [Testing](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/Testing)
Есть конечно вопрос  что было исправлено в таком случае и в какой ветке, но пока не будем об этом.
Давай сведем эту задачу к проверке этого бага, что он не воспроизводится.

**Comment by Whitetech7417** [comment]
@YuriSilenok баг не воспроизводится.
пробовал даже параметры менять , Both стояло изначально как надо, все идет по сценарию.

**Comment by YuriSilenok** [comment]
@Whitetech7417
Нужно прикрепить скрины.

**Comment by Whitetech7417** [comment]
@YuriSilenok На скрине показал один общий момент (когда появляются оба скрола)
![image](https://user-images.githubusercontent.com/38256956/47081443-5067ed80-d213-11e8-88e1-e65bbe13ade5.png)
Боковой скролл 
![image](https://user-images.githubusercontent.com/38256956/47081469-62499080-d213-11e8-99ec-c32b9dd3d60f.png)
Нижний скролл 
![image](https://user-images.githubusercontent.com/38256956/47081476-69709e80-d213-11e8-9bfe-462011ccba99.png)

**Comment by YuriSilenok** [comment]
Отлично. Зачтено. Скоро выдам новые таски.
