### ISSUE TITLE
Разработать сценарии функционального тестирования для формы Преподаватели

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#7]
Разработать сценарии  фунционального тестирования для Story #2

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Здесь вы можете посмотреть образец таблицы со сценариями.
https://docs.google.com/spreadsheets/d/18trOFX6wJZx_5x3npTJBs8UxIA6qZNcX-zqCHgG28Do/edit?ts=5af1599a#gid=0
Это не эталон, но она вам поможет, проверять я буду ее.
Необходимо будет скопировать эту гугл таблицу к себе на гугл диск и когда она будет готова скачать его как таблицу эксель и прикрепить к этому таску.
После исполнения таска необходимо заасанить таск на меня.

**Comment by NastyaFilyushkina** [comment]
[Сценарий тестирования.xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2049750/default.xlsx)

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina Пожалуйста, ознакомьтесь [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/master/README.md#%D0%A1%D1%82%D0%BE%D0%BB%D0%B1%D1%86%D1%8B-%D0%B2-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D1%85-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B5%D0%B2) с описанием столбцов в этом документе.
Эти сценарии нуждаются в доработке.
Рекомендую придти на консультацию или подготовить вопросы на завтрашнюю лекцию.

**Comment by NastyaFilyushkina** [comment]
[Сценарий тестирования (1).xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2059705/1.xlsx)

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Столбец **Mapping with matrix** заполняется только в тех строках где сценарии автоматизированы
Столбцы со статусам выполнения тестов не заполняются при составлении тестовых сценариев, а особенно статусы для автоматизации если автоматизации небыло.
В сценариях упомянута фильтрация, в стори о ней ничего не сказано. Тестовые сценарии должны покрывать только заявленную функциональность в стори.

**Comment by NastyaFilyushkina** [comment]
[Сценарий тестирования (2).xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2063072/2.xlsx)

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Зачтено, какую из какой категории вы хотели бы получить задание
- Разработать стори
- Написать сценарии
- Ручное тестирование

**Comment by NastyaFilyushkina** [comment]
Я хотела бы ручное тестирование

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
[Это ](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=F2)ссылка на Ваши сценарии на гугл диске, все оставшиеся сценарии необходимо продолжать в этой же таблице.
