### ISSUE TITLE
Вводимы данные в поля формы "Добавить преподавателя " должны автоматически изменятся.

### ISSUE THREAD

**Issue by NastyaFilyushkina** [Students-of-the-city-of-Kostroma/Student-timetable-old#72]
Затрагивает #19 
Подготовлена ветка issue-72
При вводе значений текстовых полей с буквы в нижнем регистре(первая буква значения), она заменяется на ту же букву в верхнем регистре, после "-"  регистр первой буквы тоже заменяется на верхний.
Если включен caps lock, пользователю сообщается об этом, при печати с включенным caps lock буквы меняют свой регистр (первые буквы значений переходят в верхний, остальные в нижний).
Автоматически исправленные значения можно изменить.

**Comment by YuriSilenok** [comment]
Проверить и закрыть

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Это улучшение сделано, но вы закрыли не исправленный баг #56

**Comment by YuriSilenok** [comment]
Извините, был напуган...
