### ISSUE TITLE
Написать Unit Test для класса MTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#76]
Затрагивает #2, #19, #30 
Реализовать в ветку issue-76

Написать один юнит тест для класса MTeacher
Необходимо проверит что поля в этом классе соответствуют заявленным в диаграмме

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Попробуйте сделать это, я помогу.
Вам может понадобиться 
- класс Assert который сравнивает фактическое и ожидаемое значение
- typeof(Guid) вернет тип который можно сравнивать с MTeacher.ID.GetType()

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Диаграмма в #30 отличается от полной диаграммы классов этим 
![image](https://user-images.githubusercontent.com/37622382/41311999-972bf9f2-6e8e-11e8-994f-bf15085ae854.png)
Я не исправляла в репозитории, но я скачала архив и делала там , я поправила это поле в классе MTeacher, и делала тесты, но я столкнулась с такой проблемой ,что типы полей ,которые я сравнивала с нужными типами, не могли определиться потому что они были null. Я создала конструктор без входных параметров в MTeacher, где инициализировала поля(не знаю надо так было делать или нет), и вроде бы как я сделала тест, но допустим ошибка вылетит в каком то поле, мне нужно выводить сообщение в каком именно, как это сделать?
![image](https://user-images.githubusercontent.com/37622382/41312300-605e8c4a-6e8f-11e8-90f3-f8550dd04741.png)

**Comment by YuriSilenok** [comment]
Ох, зря Вы на мой пример посмотрели, я там с потоками начинал работать что бы пример подготовить работы с фомой с точки зрения пользователя.

**Comment by YuriSilenok** [comment]
Залейте в репозиторий, я хотел бы посмотреть

**Comment by YuriSilenok** [comment]
Залейте все в ветку issue-76, это  только ваша ветка, до пул реквеста ваши измененеия ни как кого не повлияют

**Comment by NastyaFilyushkina** [comment]
Я залила

**Comment by NastyaFilyushkina** [comment]
тест в классе TestOfLib
