### ISSUE TITLE
Автоматизация тестов для метода CTeacher.AddTeacher(surname:string, name:string, middleName:string, academicDegree:string, AcademicRank:string, SizeOfTeachingExperience:byte):bool

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#81]
Затрагивает #50 
Реализовать в ветку issue-81

Автоматизироватиь тестовые [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=0&range=A11):
От issue-2-10 до issue-2-21 включительно
При автоматизации этих сценариев нужно помнить что вы тестируете котроллер (контроллер реализует бизнес-логику, ограничение и т.д.). Вам не нужно автоматизировать действия непосредственно с формой. То есть ваша написать такой тест который бы делал все то же самое, но только черерз контроллер.

**Comment by YuriSilenok** [comment]
А что у вас с этим таском?

**Comment by alvhmnv** [comment]
а вы мне на консультации тогда сказали не нужно делать его, и пока не обращать на него внимания, поэтому дали задачу дальше

**Comment by YuriSilenok** [comment]
Да, теперь припоминаю, этот таск блокировался потому что сценарии были недописаны, теперь они дописаны. #91 , можно приступать к таску. Имя тестового файла UT_CTeacher

**Comment by YuriSilenok** [comment]
Сценарии брать с вкладки 1/2018 UT

**Comment by alvhmnv** [comment]
хорошо, попробую, но  если будет возможность, назначьте ещё тасков пожалуйста

**Comment by YuriSilenok** [comment]
Ждем пул реквеста
