### ISSUE TITLE
Описать в диаграмме классов (UML) объекты из файла MTeacher.cs

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#88]
Затрагивает #30 
В ветке Testing модержится актуальная версия этого файла.
Дополнить диаграмму недостающими элементами.
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму.

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit

**Comment by YuriSilenok** [comment]
@NastyaFilyushkina 
Какая-то странная там стрелка, почему она в виде рисунка? Векторная которую я радом нарисовал не подойдет?
