### ISSUE TITLE
Написать сценарии для модульного тестирования модели MTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#89]
Затрагивает #30
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing) для модульного тестирования составлять на вкладке 1/2018 UT
Понимать что Ваши сценарии будут манипулировать не формой, а объектами без бизнес-логики.
То есть проверки публичных полей, идентификаторов или свойств сводяться к тому что-бы проверять их тип данных с которым они должны работать и что они хронят то что в них положили.
По идее методов в модели не должно быть.

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E2 я не знаю какие тесты еще можно добавить

**Comment by YuriSilenok** [comment]
#30 не так называется
> issue-30(сценарии для модульного тестирования модели MTeacher)

Тестировщик при выполнении сценария не должен использовать ничего кроме самих сценариев. Тем более нет ссылки на диаграммы, ищи свещи эту диаграмму.
> 1.Типы полей совпадают с типами заданными в диаграмме

Сценарий 1, но вот степов будет много, степ это каждое поле и ожидаемый результат соответственно будет некий тип данных, который нужно прописать
> я не знаю какие тесты еще можно добавить

**Comment by YuriSilenok** [comment]
Как вариант вы можете посмотреть сценарии issue-62, это даже правильнее так как при автоматизации теста, первый же сбой приврет тест, и остальные типы не будут проверены

**Comment by YuriSilenok** [comment]
@Natalia666503 теперь это Ваш таск

**Comment by Natalia666503** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494

**Comment by YuriSilenok** [comment]
Зачтено
