### ISSUE TITLE
Автоматизирование модульного тестирования модели MTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#90]
Затрагивает #89 
Реализовать в ветку issue-90

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
ветки 90 нет

**Comment by YuriSilenok** [comment]
1. Переключиться на вкладку Code
2. Переключиться на ветку Testing
![image](https://user-images.githubusercontent.com/14871471/41811063-164e3d8c-7711-11e8-8428-b76a73c6814b.png)
3. Ввести название ветки и нажать на кнопку создания ветки, тогда создаваемая ветка будет содержать все то что есть в ветке Testing
![image](https://user-images.githubusercontent.com/14871471/41811082-68ed947a-7711-11e8-9a8d-57927f086978.png)
