### ISSUE TITLE
Написать сценарии для модульного тестирования метода CTeacher.AddTeacher(surname:string, name:string, middleName:string, academicDegree:string, AcademicRank:string, SizeOfTeachingExperience:byte):bool

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#91]
Затрагивает #50

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E13

**Comment by YuriSilenok** [comment]
Тоже самое, тесты должны содержать ID стори а не таска на написание сценариев

**Comment by NastyaFilyushkina** [comment]
Я переделала

**Comment by YuriSilenok** [comment]
сценарий 1. не согласен с третьим шагом. Это скорее ожидаемый результат для второго пункта. То есть вы в ожидаемом результате должны прописать что метод должен вернуть false  кроме этого мы ожидаем что количество преподавателей не изменилось. Этот метод не является статическим и не может быть просто вызван, для начало нужно создать экземпляр контроллера, и вот у этого экземпляра нужно вызвать метод. Детальный сценарий это здорово, но автоматизатор будет загнан в рамки этого сценария. Допустим мы тестируем пустые строки во входных параметрах, для всех входных параметров типа строка действует одно и тоже правило, пустых строк должны приводить к отказу создания учителя и добавления его в список. Так вот, представь что один из параметров не работает, но за счет других параметров в которые поданы пустые строки  этот баг не воспроизводится. В данном случае лучше сказать что бы сценарист случайным образом выбирал один строковый параметр которому будет передаваться пустая строка, остальные будут задаваться валидными значениями. В этом случае, может быть не сразу, но мы наткнемся на этот баг. Другим способом задания этого сценария можно сказать что бы поочередно задавался один невалидный параметр, а другие валидными значениями. Это можно сделать одним циклом. Есть конечно еще вариант разделить это на отдельные тесты.

**Comment by NastyaFilyushkina** [comment]
@YuriSilenok 
Я под третьим шагом подразумеваю метод assert.isfalse/istrue, только я напутала с результатами (мне его точно удалять?). И экземпляр контроллера не создается в конструкторе тестового класса в этом случае, а мы просто заполняем его поля? Или мне все равно это надо прописывать?

**Comment by NastyaFilyushkina** [comment]
Про третий шаг до меня дошло)

**Comment by YuriSilenok** [comment]
Не уверен что я правильно понял, но у тестового класса вроде как нет конструктора (никогда им не пользовался, так как не было необходимости).
> И экземпляр контроллера не создается в конструкторе тестового класса

Контроллер нужно создавать и заполнять если это есть в сценарии в каждом тесте, не используйте поля тестового класса.
> , а мы просто заполняем его поля? Или мне все равно это надо прописывать?

**Comment by YuriSilenok** [comment]
Если у вас вопрос, вы его задаете в комментариях, и мне на почту придет этот вопрос ос всеми ссылками, можно не асанить на меня этот так, асанить лучше когда таск нужно проверить.

**Comment by NastyaFilyushkina** [comment]
Так я сделала

**Comment by YuriSilenok** [comment]
Не хотел бы вас расстраивать, но циклов в тестовых сценариях не должно быть.
> 1.В цикле для экземпляр
Это ведь число должно быть, а не строка.
> sizeOfTeachingExperience="32"
Это не степ, это ожидаемый результат ко второму шагу. Ожидаемый результат проверяется после выполнения степа. То есть после вызова методы вы должны проверить что в писке преподавателей количество элементов увеличилось на 1.
> Сделать проверку увеличилось ли количество элементов в списке преподавателей

**Comment by NastyaFilyushkina** [comment]
Еще сделала ввод некорректных данных

**Comment by YuriSilenok** [comment]
Ожидаемые результаты должны быть максимально точными, если что-то увеличивается, нужно сказать на сколько или во сколько, дать какую-то математическую зависимость, если мы точно не можем сказать, что должно быть 4 элемента в списке.

**Comment by NastyaFilyushkina** [comment]
Я указала количество.
