### ISSUE TITLE
Написать сценарии для модульного тестирования метода CTeacher.SaveTeacher(ID:Guid, surname:string, name:string, middleName:string, academicDegree:string, AcademicRank:string, SizeOfTeachingExperience:byte):bool

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#92]
Затрагивает #51

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E31

**Comment by YuriSilenok** [comment]
Почему это так, почему это не в одну строку?
> ![image](https://user-images.githubusercontent.com/14871471/41812426-3eb6cbbc-772b-11e8-8dcf-ba2f65f23bc0.png)

**Comment by NastyaFilyushkina** [comment]
Уточнила что правильные параметры-это не пустые,такого же типа как 
указаны в параметрах метода.

**Comment by YuriSilenok** [comment]
Скажите, если я задам полю фамилия, вот такое значение типа string "98w&%W", это правильно? я хочу сказать что вы должны давать тестовые случаи, более конкретные.

**Comment by NastyaFilyushkina** [comment]
Я просто думаю это будет контролироваться на уровне формы, для создания преподавателя мы же сделали игнорирование символов, кстати это еще один баг, при копировании текста в поле неправильные символы не будут игнорироваться. Это заводить как новый баг или писать в #56 ? Или может просто запретить вставку в поля формы?

**Comment by YuriSilenok** [comment]
Не про таск
Я буду задачи накидывать по старой схеме, те задачи которые останутся не реализованными, а баллы все получены, перекинуть на меня с комментарием что курсовик сдан, или можете перекинуть эти задачи самостоятельно на того человека которому хотите помочь.

**Comment by YuriSilenok** [comment]
На самом деле это очень философский вопрос, должен ли пользователь иметь возможность вводить запрещенные символы, есть собственно несколько подходов к этому, первый когда пользвователь не может ввести, когда он может ввести но его предупреждают тут же об это и когда он может ввести и его предупреждают при попытке отправки данных. Мы ни где это не определяли какой у нас именно вариант. Если смотреть на то как устроен сам шаблон (опять же читать о вариантах использования этого шаблона можно читать бесконечно долго), то можно выделить несколько категорий реализуемых ограничений (или бизнес-правил). 
- Ограничения одного неделимого поля. Это может быть просто фамилия (на символы) или возраст (на диапазон). Это можно (и на мой взгляд нужно) реализовывать на уровне модели. Лучше их реализовывать через свойства.
- Ограничение затрагивающие несколько простых полей в пределах одного экземпляра объекта. Так же на мой взгляд должны быть реализованы в пределах модели при помощи свойств. Например мы не можем создать преподавателя к которого возраст 20 лет, а стаж 30 лет.
- Ограничение затрагивающие несколько объектов. Точно должны реализовываться в контроллере. Например в системе не должно быть двух сотрудников с одним и тем же номером и серией паспорта
Вопрос, что же остается на роль представление, ввод и вывод данных, то есть по идее пользователь может вводить что угодно и может получить некий ответ, если ошибся.
Такое количество багов на самом деле мы получили из-за меня, я начал проект с реализации представлений, надеясь на то что так будет проще студентам, но это оказалось не эффективно.
По поводу контроля, по идее у нас должна была быть форма которая добавляет преподавателя или другой объект. и в своем поле она должна содержать экземпляр модели, с которым общается форма посредством полей. то же само и с изменением объектов.
> Я просто думаю это будет контролироваться на уровне формы
Баги не заводи. так как этот таск не направлен на выполнение тестов

**Comment by YuriSilenok** [comment]
Если преподаватель добавляется в список преподавателей, значит этот список должен увеличиваться, это тоже должно быть в ожидаемом результате.

**Comment by NastyaFilyushkina** [comment]
Метод изменяет значения существующего объекта MTeacher значениями из входных параметров метода.Метод вернет истину если удалось найти и изменить преподавателя в списке, иначе вернет ложь.. Мы же просто изменяем выбранного, зачем добавлять  в список?

**Comment by YuriSilenok** [comment]
Да, я перепутал с другими сценариями, в любом случае для этого метода должны ожидать что количество элементов в списке не меняется. Делов в том что прогроаммисты, иногда, что бы поработать с неким элементом могут забирарать элемент из списка, а потом ложить его обратно.

**Comment by YuriSilenok** [comment]
Что бы это лучше понять, мы должны проверять те элементы системы, с которыми хоть как-то работает этот метод. В нашем случае это только список.
> Да, я перепутал с другими сценариями, в любом случае для этого метода должны ожидать что количество элементов в списке не меняется. Делов в том что прогроаммисты, иногда, что бы поработать с неким элементом могут забирарать элемент из списка, а потом ложить его обратно.

**Comment by YuriSilenok** [comment]
Кому балл дарить будем?
