### ISSUE TITLE
Написать сценарии для модульного тестирования метода CTeacher.DeleteTeacher(ID:Guid):bool

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#93]
Затрагивае #52

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E9

**Comment by YuriSilenok** [comment]
Вы пишете сценарии для тестирования некоторой стори 52, судя из заголовков ваших сценариев вы пишите сценарии для тестирования сценариев.

**Comment by YuriSilenok** [comment]
Ошибочное - видимо негативный тест, сначала нужно делать позитивный тест, проверить что вообще работает на корректных данных, а потом уже ломать изо всех сил. И информации о том что это негативный тест пишется в Discription. Я понимаю что у нас всего один входной параметр для этого метода, но все равно нужно прописывать кто пустой, так как по началу я подумал о пустом списке преподавателей. Опять же третий степ это ожидаемый результат для второго степа.
> "Ошибочный, пустое значение"

**Comment by YuriSilenok** [comment]
В целом нормально, только когда вы автоматизируете, то столбец **Mapping with matrix** заполняется, у него указывается имя файла в который писались автоматические тесты
