### ISSUE TITLE
Написать сценарии для модульного тестирования метода CTeacher.GetData():string[,]

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#94]
Затрагивает #53

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E17

**Comment by YuriSilenok** [comment]
Сценарий 1. У нас нет пустого массива, есть пустой список преподавателей, массив мы получаем в результате вызова массива. По поводу ожидаемого результат, тот кто будет исполнять этот сценарий, он не в курсе как правильно и не должен сидеть и разбираться в этом, эта задача как раз того кто пишет этот сценарий. В ожидаемом результате нужно будет сказать что полученный двумерный массив будет содержать одну строку с названиями ключей из перечисления в порядке их числового представления.

**Comment by YuriSilenok** [comment]
#53 звучит как **Реализация метода CTeacher.GetData():string[,]** именно этот текст и нужно указывать
> issue-53(сценарии для модульного тестирования метода CTeacher.GetData():string[,] )

Я не понимаю почему Вы ставите переносы в ручную?
> ![image](https://user-images.githubusercontent.com/14871471/41811964-2aec3abc-7722-11e8-8397-dd20309aae67.png)

Кто-то автоматизировал сценарии?

**Comment by NastyaFilyushkina** [comment]
Потому что мой ноут не хочет делать перенос хорошо, и мне приходится делать самой. Никто не автоматизировал. Заголовок изменила

**Comment by YuriSilenok** [comment]
Есть три режима отображения текста в ячейке, возможно всё дело вних? Если это не поможет, хотел бы увидеть скрин проблемы
![image](https://user-images.githubusercontent.com/14871471/41812730-b8874106-7730-11e8-8db0-e937acfacace.png)

> Потому что мой ноут не хочет делать перенос хорошо, и мне приходится делать самой.

**Comment by YuriSilenok** [comment]
А чего тогда в ячейке **Automated** указано что уже автоматизировано, если планируется автоматизировать ставиться **To be**
> Никто не автоматизировал.

**Comment by NastyaFilyushkina** [comment]
Я раньше не видела этой кнопки, спасибо

**Comment by YuriSilenok** [comment]
В любой непонятной ситуации нужно писать письмо с вопросом.
> Я раньше не видела этой кнопки, спасибо
Нужно ли говорить, что нужно пробежаться по сценариям и для своих сценариев в ненужных местах убрать искусственные переносы, если встретятся у других такое (специально не искать) сообщить в каких стори это присутствует.

**Comment by NastyaFilyushkina** [comment]
Исправила
