### ISSUE TITLE
Написать сценарии для модульного тестирования метода CTeacher.GetData(columnName:string, order:bool):string[,]

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#95]
Затрагивает #54

**Comment by NastyaFilyushkina** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=683731494&range=E25 
Я думаю при неправильном заголовке должно выбрасываться исключение, но я не знаю надо ли вообще эти тесты на неправильные значения.

**Comment by YuriSilenok** [comment]
Меня этот вопрос тоже гнобил. Мы можем или проигнорировать и ожидать массив в не сортированном виде или выбрасывать исключение с текстом что столбец такой-то не найден. ДАвай все же будем ожидать исключение. Это хоть и ресурсоемко, но вы сможем сообщить о неудаче при сортировке, а если не выбрасывать, то пользователь этого метода будет думать что он отсортирован и ни как об этом не узнает. Нужно определиться с текстом исключения. Пусть это будет, "Сортируемый столбец <имяПереданногоСтобца> не найден".

**Comment by NastyaFilyushkina** [comment]
Исключения заполнила, вроде все сделано

**Comment by YuriSilenok** [comment]
Массив будет не пустым, у него будет одна строка с именами столбцов
> 1.Получен пустой двумерный массив

**Comment by YuriSilenok** [comment]
Должны быть конкретные значения, так как тестировщик увидев в столбце 100, 9 подумает что это нормальная сортировка. но это нормально только для строк, а для чисел это не верно
> "1.Получен двумерный массив
 содержащий
 соответсвующие значения 
из списка преподавателей 
отсортированый в выбранном
 порядке"

**Comment by NastyaFilyushkina** [comment]
Можно я просто уточню, что "получен массив отсортированный в выбранном порядке (буквы по алфавиту/в обратном алфавитном порядке, числа по возрастанию/убыванию)" ?

**Comment by YuriSilenok** [comment]
Это минимум, но нужно однозначно указать какой столбец какому правилу сортировки будет соответствовать.

**Comment by YuriSilenok** [comment]
Зачтено
