### ISSUE TITLE
Проектирование модели для объекта Аудитория

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#96]
Основываясь на описании формы Аудитории #4 [дополнить ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)диаграмму классов в нотации UML

**Comment by TanyaMalis** [comment]
@YuriSilenok 
На номер аудитории и ее вместительность поставила int или byte достаточно было?

**Comment by YuriSilenok** [comment]
- Какой номер аудитории в которой у нас лекция проходит?
-Существует правило, если над данными есть смысл выполнять арифметические операции, то это числовой тип данных, а например номер телефона, номер страхового полиса, это все строки, хотя состоят только из цифр.

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Да,  этот номер аудитории 
Я посмотрела просто в модели MTeacher, там стаж преподавателя тоже byte стоит, решила так же сделать

**Comment by TanyaMalis** [comment]
Поменять их на string?

**Comment by YuriSilenok** [comment]
Со стажем можно делать мат операции, например отобрать тех у кого стаж больше 10 лет, или посчитать суммарный стаж всех сотрудников. Спроектируйте, потом посмотрю

**Comment by TanyaMalis** [comment]
Реализация этой модели в таск тоже входит?

16 июня 2018 г. 23:52 пользователь "Yuri Silenok" <notifications@github.com>
написал:

**Comment by TanyaMalis** [comment]
https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit

**Comment by TanyaMalis** [comment]
@YuriSilenok 
Таск зачтен?
