### ISSUE TITLE
Проектирование модели для объекта Группа

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable-old#97]
Основываясь на описании формы Группы #5  [дополнить ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing)диаграмму классов в нотации UML

**Comment by Natalia666503** [comment]
https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit

**Comment by YuriSilenok** [comment]
Зачтено
